### ISSUE TITLE
Boids Scatter on Flock Screen Wrap

### ISSUE THREAD

**Issue by alexkay6** [JohnPeel/flock-rs#1]
The Flock will be all nicely flying then when about half of them have passed the screen wrap point the other half will scatter and double back across the screen rather than continue with the wrap, this is probably to do with how they calculate there distance from the average and don't factor screen wrap.

**Comment by JohnPeel** [comment]
Yeah, I'm still working on what math I can use to counteract that.

I thought maybe wrapping boids father than half the diagonal of the board back to the other end before calculating distance, but I'm not sure I have it correct.

**Comment by JohnPeel** [comment]
In the calculation of cohesion, I accounted for screen wrap in the difference between the average position of the flock and the boids current position.

It now does a lot better, but you can still see a bit of scattering when hitting a corner.

**Comment by JohnPeel** [comment]
Okay, I've also accounted for screen wrap inside of calculate_averages when calculating the average position of a flock, and all of the scattering is pretty much gone (at least after the first few seconds of running, which is probably because I create flocks using random positions and a velocity of zero).
